W3ChampionsStatisticService/W3ChampionsStats/MmrDistribution/MmrDistributionHandler.cs

the math.abs(x-r) < 25 part is looking at intervals of length 50

Fix MMRs being counted twice

---

W3ChampionsStatisticService/Admin/Admins.cs

In order to debug/add features to website admin pages.

added cepheid#1467 to admins

---

W3ChampionsStatisticService/Matches/MapName.cs

Resolves the following issue on the website:

Fixes an issue with mapNames for the website

---

W3ChampionsStatisticService/PlayerProfiles/MmrRankingStats/PlayerMmrTimeline.cs
W3ChampionsStatisticService/PlayerProfiles/MmrRankingStats/PlayerMmrTimelineHandler.cs
W3ChampionsStatisticService/PlayerProfiles/PlayerRepository.cs
W3ChampionsStatisticService/PlayerProfiles/PlayersController.cs
W3ChampionsStatisticService/Ports/IPlayerRepository.cs
W3ChampionsStatisticService/Startup.cs
WC3ChampionsStatisticService.UnitTests/PlayerTests.cs

With this PR the PlayerMmrTimelineHandler is functional.

Update: MMR Timeline for individual players

---

W3ChampionsStatisticService/Matches/MatchQueryHandler.cs
W3ChampionsStatisticService/Matches/MatchesController.cs
W3ChampionsStatisticService/Matches/PlayerOverviewMatches.cs
W3ChampionsStatisticService/Matches/PlayersObfuscator.cs
W3ChampionsStatisticService/Startup.cs

This is a step needed to implement active streams on home page and may be on ongoing matches page

add twitch to players in ongoing matches

---

.vscode/launch.json
W3ChampionsStatisticService/Tournaments/Models/TournamentMatch.cs

- add date to tournament matches
- fixed launch config

Date to tournament matches and fix launch config

---

W3ChampionsStatisticService/W3ChampionsStatisticService.csproj

removed line from proj file

---

W3ChampionsStatisticService/Admin/AdminController.cs
W3ChampionsStatisticService/Admin/AdminRepository.cs
W3ChampionsStatisticService/Admin/FloProxies.cs
W3ChampionsStatisticService/Admin/ProxyResponse.cs
W3ChampionsStatisticService/Admin/ProxyUpdate.cs
W3ChampionsStatisticService/Ports/IAdminRepository.cs
W3ChampionsStatisticService/Ports/IPlayerRepository.cs
W3ChampionsStatisticService/Startup.cs

added new Admin Repository for admin functions, may refactor other admin functions here in future.

Proxy in admin

---

W3ChampionsStatisticService/PadEvents/MatchmakingServiceRepo.cs

Reverts w3champions/website-backend#148

Revert "int"

---

W3ChampionsStatisticService/Admin/Portraits/PortraitCommandHandler.cs
W3ChampionsStatisticService/PersonalSettings/PersonalSetting.cs
WC3ChampionsStatisticService.UnitTests/PersonalSettingstests.cs
WC3ChampionsStatisticService.UnitTests/PortraitActionTests.cs

Portraits where not always added due to "SpecialPictures" property being null in PersonalSetting
Merging in my changes to the work-in-progress branch

Handling setting Portraits when "SpecialPictures" is null

---

W3C.Domain/MatchmakingService/MatchmakingContracts/GetSeasonMapsResponse.cs
W3C.Domain/MatchmakingService/MatchmakingContracts/MapContract.cs
W3C.Domain/MatchmakingService/MatchmakingContracts/SeasonMapContract.cs
W3C.Domain/MatchmakingService/MatchmakingServiceClient.cs
W3ChampionsStatisticService/Maps/MapsController.cs

[W3C-143] Create API for getting current season maps

---

W3ChampionsStatisticService/PersonalSettings/PersonalSetting.cs

Also fixes the casing for TotalPictureRange

Fix Total wins < 5

---

W3ChampionsStatisticService/Matches/MatchRepository.cs
W3ChampionsStatisticService/Matches/MatchesController.cs
W3ChampionsStatisticService/Matches/OngoingMatchesCache.cs
W3ChampionsStatisticService/Ports/IMatchRepository.cs

Backend code for sorting live matches by mmr. Should be merged in before the frontend PR with the same jira issue number.

[W3C-30] Add mmr sorting for ongoing matches

---

W3ChampionsStatisticService/Matches/MatchesController.cs

Added caching for count of matchups

---

W3ChampionsStatisticService/Matches/MatchesController.cs

W3 c 164 api matches

---

W3C.Domain/ReplayService/ReplayServiceClient.cs
W3ChampionsStatisticService/Replays/ReplaysController.cs
W3ChampionsStatisticService/Startup.cs

[W3C-168] add replay download

---

W3ChampionsStatisticService/PlayerProfiles/GameModeStats/GameModeStatQueryHandler.cs
W3ChampionsStatisticService/PlayerProfiles/PlayerRepository.cs
W3ChampionsStatisticService/PlayerProfiles/PlayersController.cs
W3ChampionsStatisticService/Ports/IPlayerRepository.cs
W3ChampionsStatisticService/Services/MatchmakingProvider.cs
W3ChampionsStatisticService/Services/PersonalSettingsProvider.cs
W3ChampionsStatisticService/Services/PlayerService.cs
W3ChampionsStatisticService/Services/PlayerStatsService.cs
W3ChampionsStatisticService/Startup.cs
W3ChampionsStatisticService/W3ChampionsStats/MapsPerSeasons/GamesPlayedOnMap.cs
W3ChampionsStatisticService/W3ChampionsStats/W3CStatsController.cs
WC3ChampionsStatisticService.UnitTests/Clans/ClanTests.cs
WC3ChampionsStatisticService.UnitTests/Performance/DBPerformanceTest.cs
WC3ChampionsStatisticService.UnitTests/PersonalSettings/PersonalSettingsTests.cs
WC3ChampionsStatisticService.UnitTests/Player/PlayerOverviewTests.cs
WC3ChampionsStatisticService.UnitTests/Player/PlayerTests.cs
WC3ChampionsStatisticService.UnitTests/Ranks/RankTests.cs
WC3ChampionsStatisticService.UnitTests/Rewards/PortraitCommandTests.cs
WC3ChampionsStatisticService.UnitTests/Statistics/PlayerStatsTests.cs

Continuation of https://github.com/w3champions/website-backend/pull/225
Map names for global statistics
Extract Player service from Player repository to avoid spaghetti.

W3 c 86 map descriptions on statistics 2

---

W3C.Domain/MatchmakingService/MatchmakingServiceClient.cs
W3ChampionsStatisticService/Admin/AdminController.cs

Frontend PR:
https://github.com/w3champions/website/pull/598
Matchmaking PR:
https://github.com/w3champions/matchmaking-service/pull/274

Rework banned players

---

W3C.Domain/MatchmakingService/MatchmakingServiceClient.cs

Website PR: https://github.com/w3champions/website/pull/605
Matchmaking PR: https://github.com/w3champions/matchmaking-service/pull/276

Add banInsertDate property

---

W3C.Domain/MatchmakingService/MatchmakingServiceClient.cs

Website PR: https://github.com/w3champions/website/pull/613
Matchmaking PR: https://github.com/w3champions/matchmaking-service/pull/281

Add author field to ban

---

W3ChampionsStatisticService/W3ChampionsStats/MmrDistribution/MmrDistributionHandler.cs

Backend fix for https://github.com/w3champions/website/pull/617

Fix typo top25PercentIndex

---

W3C.Contracts/Admin/Moderation/LoungeMute.cs
W3C.Domain/MatchmakingService/MatchmakingServiceClient.cs
W3ChampionsStatisticService/Admin/AdminController.cs
W3ChampionsStatisticService/Moderation/ModerationController.cs

website PR: https://github.com/w3champions/website/pull/648
matchmaking PR: https://github.com/w3champions/matchmaking-service/pull/294
chat-service PR: https://github.com/w3champions/chat-service/pull/5

Create lounge mutes

---

W3ChampionsStatisticService/Program.cs
W3ChampionsStatisticService/Startup.cs
W3ChampionsStatisticService/W3ChampionsStatisticService.csproj
W3ChampionsStatisticService/W3ChampionsStats/HourOfPlay/HourOfPlayStatHandler.cs

Adds Serilog to enable logging to file and directory browsing of these log files in test and production.

Add serilog

---

W3C.Domain/MatchmakingService/MatchmakingServiceClient.cs
W3ChampionsStatisticService/Maps/MapsController.cs

website PR: https://github.com/w3champions/website/pull/684
matchmaking PR: https://github.com/w3champions/matchmaking-service/pull/302

Allow setting map id on map save

---

W3ChampionsStatisticService/PlayerProfiles/PlayerRepository.cs
W3ChampionsStatisticService/PlayerProfiles/PlayersController.cs
W3ChampionsStatisticService/PlayerStats/GameLengthForPlayerStatistics/GameLengthForPlayerStatisticsHandler.cs
W3ChampionsStatisticService/PlayerStats/GameLengthForPlayerStatistics/PlayerGameLength.cs
W3ChampionsStatisticService/PlayerStats/GameLengthForPlayerStatistics/PlayerGameLengthStat.cs
W3ChampionsStatisticService/Ports/IPlayerRepository.cs
W3ChampionsStatisticService/Startup.cs
WC3ChampionsStatisticService.UnitTests/Player/PlayerGameLengthStatsTests.cs

Description here: 
https://github.com/w3champions/website-backend/pull/281

feat: add player game length handler

---

W3ChampionsStatisticService/Matches/MatchesController.cs

Add new params season for GetMatches API Call

Add season as query param for GetMatches request

---

W3ChampionsStatisticService/Matches/MatchRepository.cs
W3ChampionsStatisticService/Matches/MatchesController.cs
W3ChampionsStatisticService/Ports/IMatchRepository.cs
W3ChampionsStatisticService/W3ChampionsStatisticService.csproj
WC3ChampionsStatisticService.UnitTests/Matchups/MatchupRepoTests.cs

Add test and better handling of last season

Get last season from db

---

W3ChampionsStatisticService/Maps/MapsController.cs
W3ChampionsStatisticService/WebApi/ActionFilters/BearerHasPermissionFilter.cs
WC3ChampionsStatisticService.UnitTests/Auth/BearerTest.cs

Change to classic bearer auth instead of using query params

Change bearer auth part1

---

W3ChampionsStatisticService/Clans/ClanController.cs
W3ChampionsStatisticService/Startup.cs
W3ChampionsStatisticService/WebApi/ActionFilters/BearerCheckIfBattleTagBelongsToAuthAttribute.cs
W3ChampionsStatisticService/WebApi/ActionFilters/BearerCheckIfBattleTagBelongsToAuthFilter.cs

Clans API bearer auth

---

W3ChampionsStatisticService/Replays/ReplaysController.cs

I need a way to download replays/view chat logs for drawn games

Allow querying replays by FLO id directly

---

W3C.Contracts/Matchmaking/ExtendedGameMap.cs
W3C.Contracts/Matchmaking/GameMap.cs
W3C.Contracts/Matchmaking/MapContract.cs

is_twelve_p field, remove ExtendedGameMap

---

W3ChampionsStatisticService/Matches/MatchRepository.cs
W3ChampionsStatisticService/Matches/Matchup.cs
W3ChampionsStatisticService/Ports/IMatchRepository.cs

Pipeline failed on `dotnet format` so this PR is running it first to fix the failure.

Run dotnet format to fix build pipeline

---

Directory.Packages.props
W3ChampionsStatisticService/Program.cs
W3ChampionsStatisticService/W3ChampionsStatisticService.csproj

Add logging to console to allow the logs to be scraped.
Also update Serilog and Serilog.Sinks.Console as they were way too old.

Add console logging and upgrade loggers

---

W3C.Contracts/Matchmaking/GameMode.cs

Reverts w3champions/website-backend#416
Revert until I figure out a way to make it conditional

Revert "Add risk europe ladder"

---

W3ChampionsStatisticService/W3ChampionsStats/GameLengths/GameLengthStat.cs

The Game Length Statistics needed to get some updates:
This config will only take effect if the entire GameLengthStat document for the mode is deleted as that's the only moment when the data will be re-seeded from the config. Backfilling gamelength data is not an option as our event processing system does not support partial reprocessing. Speak the deployment will not actually change any of the data.
Will reduce from 180 min to 140min. The change can be done without data loss by removing the upper buckets in the GameLengthStat document for the game mode.
Will increase from 60 min to 120 min. This change will require us to wipe all the data for the game mode.
Will increase from 60 min to 100min. This change will require us to wipe all the data for the game mode.

Adjust Game Length statistics graph

---

W3ChampionsStatisticService/Hubs/WebsiteBackendHub.cs

Need to keep this for backwards compatibility.

Backwards  compatible zero arg handler

---

W3C.Contracts/Admin/Permission/Permission.cs
W3ChampionsStatisticService/Admin/AdminController.cs
W3ChampionsStatisticService/Admin/AdminRepository.cs
W3ChampionsStatisticService/Admin/SmurfDetection/AddIgnoredIdentifierDto.cs
W3ChampionsStatisticService/Admin/SmurfDetection/BackendResponseDto.cs
W3ChampionsStatisticService/Admin/SmurfDetection/BattleTagLoginStatistics.cs
W3ChampionsStatisticService/Admin/SmurfDetection/ExplanationStep.cs
W3ChampionsStatisticService/Admin/SmurfDetection/IdentifierGroup.cs
W3ChampionsStatisticService/Admin/SmurfDetection/IgnoredIdentifier.cs
W3ChampionsStatisticService/Admin/SmurfDetection/QuerySmurfsDto.cs
W3ChampionsStatisticService/Admin/SmurfDetection/SmurfDetectionResult.cs
W3ChampionsStatisticService/Ports/IAdminRepository.cs

Adds the UI backend for the new smurf checker frontend.
This should be backwards compatible.

[Smurf detection] Add new UI backend

---

Directory.Packages.props
W3ChampionsStatisticService/Program.cs
W3ChampionsStatisticService/W3ChampionsStatisticService.csproj

Add the right formatter so that logs get properly output for grafana

Add loki log formatter

---

Directory.Packages.props
W3ChampionsStatisticService/Program.cs
W3ChampionsStatisticService/W3ChampionsStatisticService.csproj

use rendered message insteak of loki formatter

Fix logging

---

W3C.Domain/MatchmakingService/MatchEventDtos.cs
W3ChampionsStatisticService/Matches/Matchup.cs
W3ChampionsStatisticService/Matches/PlayerOverviewMatches.cs
W3ChampionsStatisticService/Matches/Team.cs
WC3ChampionsStatisticService.UnitTests/Helpers/TestDtoHelper.cs
WC3ChampionsStatisticService.UnitTests/Matchups/MatchupTests.cs

The MatchFinishedEvent already has the MatchRanking property. This now passes it through to the Matchup object so we can use it in the frontend

Add MatchRanking to Matchup so that we can display game result order
