w3champions/website-backend

W3ChampionsStatisticService/W3ChampionsStats/GameLengths/GameLengthStat.cs
Trying to get my first PR in, which is meant to address this issue: https://github.com/w3champions/w3champions-ui/issues/210
I noticed that the root cause seemed to be with the data returned from https://statistic-service.w3champions.com/api/w3c-stats/games-lengths (and not the UI itself). So this should now return game lengths up to **3 hours** for **FFA** (i.e `360 * 30 sec = 180 min`), while the **other game modes** remain at **1 hour** (i.e. `120 * 30 sec = 60 min`).
=> Return game lengths up to 3 hours for FFA (others remain at 1 hour)

W3ChampionsStatisticService/PlayerProfiles/PlayerRepository.cs, W3ChampionsStatisticService/Ports/IPlayerRepository.cs, W3ChampionsStatisticService/W3ChampionsStats/MmrDistribution/MmrDistributionHandler.cs, W3ChampionsStatisticService/W3ChampionsStats/W3CStatsController.cs, WC3ChampionsStatisticService.UnitTests/PlayerOverviewTests.cs
I extended the Load  mrrs function. Now its possible to have parameters of Gateway and Gamemode in the API.
So the issue in the UI can be handled https://github.com/w3champions/w3champions-ui/issues/242
The default values are Gateway Europe and Gamemode 1v1 as this seemed to be (or should be) the default. So it should be backward compatible with any functions in UI at the moment.
All tests in my projects passed, but it seems LoadMMRsDitribution function is not involved in any test.
Also tested on local Mongodb and works.
If you want to have any further changes, let me know pls.
When there are cases the old function is still needed I could change it to an overload function.
=> Extend mmr distribution

W3ChampionsStatisticService/PlayerProfiles/MmrRankingStats/PlayerMmrTimeline.cs, W3ChampionsStatisticService/PlayerProfiles/MmrRankingStats/PlayerMmrTimelineHandler.cs, W3ChampionsStatisticService/PlayerProfiles/PlayerRepository.cs, W3ChampionsStatisticService/Ports/IPlayerRepository.cs, W3ChampionsStatisticService/Startup.cs, WC3ChampionsStatisticService.UnitTests/PlayerTests.cs
This relates to issue #215 in UI (https://github.com/w3champions/w3champions-ui/issues/215)
The goal is to create an interface for the frontend to load MMR data to create a graph. With the parameters battletag, race, gateway and season, specific data could be easily queried from the backend to display graphs for various constallations.
As I'm new to the project, I'm not sure whether the mmr values used are the correct ones. In the "PlayerMmrTimelineHandler", once im using "Match" (Update()) and once "Matchup" (CreateMmrTimeline()) to get the mmr values. Not sure if this is problematic. From "Match" I can get a "PlayerMMrChange", which has both "mmr" and "updatedMmr". Which one to use?
I added a test, but I'm getting weird values for the mmr numbers. They seem to be random, not sure why. …
=> MMR Timeline for individual players

W3ChampionsStatisticService/PlayerProfiles/GameModeStats/GameModeStatQueryHandler.cs
There are some ranks in season 0, that do not have a league
for the corresponding league constellation, e.g. 0_Europe_GM_1v1.
Rather than rely on the try/catch to catch the Linq exception on
the Single call, use SingleOrDefault specifically for season 0,
so that we avoid the bloating of the logs, but can still catch
exceptions on later seasons.
should resolve w3champions/w3champions-ui#287
=> Add handling for missing leagues in season 0.

W3ChampionsStatisticService/CommonValueObjects/Race.cs, W3ChampionsStatisticService/CommonValueObjects/RaceExtensions.cs, W3ChampionsStatisticService/Matches/Matchup.cs, W3ChampionsStatisticService/Matches/PlayerOverviewMatches.cs, W3ChampionsStatisticService/PadEvents/MatchEventDtos.cs, WC3ChampionsStatisticService.UnitTests/MatchupDetailTest.cs, WC3ChampionsStatisticService.UnitTests/TestDtoHelper.cs
Use the player's hero selection to determine, if possible,
which race they were assigned from the random selection.
Assigned to a new member property, so that it can be used
separately for statistical computations/display. If the
player's race is not random, then null is assigned to the
random race member. If it cannot be determined which race
was assigned, then random is set for both the player race
as well as the random race.
First step required for handling w3champions/w3champions-ui#281
sanely in multiple UI components. Also, computed in the record so
that statistics can be computed at a later time.
Does not backfill previous matches.
=> Add random race to matchup players.

W3ChampionsStatisticService/Admin/AdminController.cs, W3ChampionsStatisticService/Admin/Portraits/PortraitCommandHandler.cs, W3ChampionsStatisticService/Admin/Portraits/PortraitDefinition.cs, W3ChampionsStatisticService/Admin/Portraits/PortraitRepository.cs, W3ChampionsStatisticService/Admin/Portraits/PortraitsDefinitionCommand.cs, W3ChampionsStatisticService/Ports/IPortraitRepository.cs, WC3ChampionsStatisticService.UnitTests/IntegrationTestBase.cs, WC3ChampionsStatisticService.UnitTests/PortraitActionTests.cs
Portraits can now be assigned to "groups" in the database, this means we can bulk-add portraits by getting those of a certain group, e.g. for patreon tiers: "bronze" / "silver" / "gold"
=> Portraits can now be grouped by a string identifier

W3ChampionsStatisticService/PlayerProfiles/PlayerRepository.cs, W3ChampionsStatisticService/ReadModelBase/MongoDbRepositoryBase.cs
seanmcnabb (community dev who is building a stats tool for streams) requested that I make the endpoints which query battletag case-insensitive.
I know this has been done in at least one other endpoint, I wanted to make it universal.
=> endpoints case insensitive

W3ChampionsStatisticService/Admin/Portraits/PortraitCommandHandler.cs, W3ChampionsStatisticService/PersonalSettings/PersonalSettingsController.cs, W3ChampionsStatisticService/PersonalSettings/PersonalSettingsRepository.cs, W3ChampionsStatisticService/Ports/IPersonalSettingsRepository.cs, WC3ChampionsStatisticService.UnitTests/IntegrationTestBase.cs, WC3ChampionsStatisticService.UnitTests/PersonalSettingstests.cs, WC3ChampionsStatisticService.UnitTests/PortraitActionTests.cs
- Removed "populate-country-codes" route to prevent ddos.
- Refactored the update schema method to be accessible from `PersonalSettingsRepository`
- When `Load` or `LoadMany` in PersonalSettings collections, the setting will be checked to see if the schema needs to be updated, then updated accordingly if necessary.
- Added tests for above
=> refactor "UpdateSchema" to PersonalSettings

W3ChampionsStatisticService/PlayerProfiles/PlayerRepository.cs, W3ChampionsStatisticService/PlayerProfiles/PlayersController.cs, W3ChampionsStatisticService/PlayerProfiles/RaceStats/PlayerRaceStatPerGateway.cs, WC3ChampionsStatisticService.UnitTests/Player/PlayerTests.cs
The following database changes are needed before the fix is deployed:
Run the following script in mongosh to extract the battletag from the id into a separate field/property:
let requests = [];
db.PlayerRaceStatPerGateway.aggregate([
{
$addFields: {
BattleTag: {
$arrayElemAt: [
{
"$split": [
{
$toLower: "$_id"
},
"_"
]
},
1
]
}
}
}
]).forEach(document => { 
requests.push({ 
"updateOne": { 
"filter": { "_id": document._id }, 
"update": { 
"$set": { 
"BattleTag":document.BattleTag, 
}
}
}
});
if ( requests.length === 500 ) { 
// Execute per 500 ops and re-init
db.PlayerRaceStatPerGateway.bulkWrite(requests); 
requests = []; 
}}
);
if(requests.length > 0) {
db.PlayerRaceStatPerGateway.bulkWrite(requests);
}
2. Add the following index to PlayerRaceStatPerGateway:
{
v: 2,
key: { BattleTag: 1, …
=> W3 c 163 api player stats battle tag race stats

W3ChampionsStatisticService/Admin/GlobalChatBan.cs
A mute-ban expiry date at year 2060 causes an Int32 overflow.
```
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HMOPIIQO8HN7", Request id "0HMOPIIQO8HN7:00000003": An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonReaderException: JSON integer 2871072000 is too large or small for an Int32. Path 'player_bans[66].ban_expires_at.seconds', line 1, position 13905.
```
A signed integer can only hold a value of 2,147,483,648, so 2,871,072,000 caused overflow. Changed to uint (unsigned int) to allow values up to 4,294,967,295 (year 2106).
=> Set PlayerChatBanTimestamp to use uint instead of int to avoid overflow

W3ChampionsStatisticService/PlayerStats/PlayerStatsController.cs, W3ChampionsStatisticService/PlayerStats/RaceOnMapVersusRaceStats/PlayerRaceOnMapVersusRaceRatio.cs, W3ChampionsStatisticService/PlayerStats/RaceOnMapVersusRaceStats/PlayerRaceOnMapVersusRaceRatioView.cs, W3ChampionsStatisticService/Services/PlayerStatsService.cs
If a player has not played any 1v1 matches this season, `var mapAndRaceStat = await _playerStatsRepository.LoadMapAndRaceStat(battleTag, season);` in `W3ChampionsStatisticService/Services/PlayerStatsService.cs` is null, and we get a 500 error.
=> fix case when mapAndRaceStat is null

W3ChampionsStatisticService/W3ChampionsStatisticService.csproj
Making this PR instead of dependabot's PR https://github.com/w3champions/website-backend/pull/220 because it only wanted to upgrade `Swashbuckle.AspNetCore.SwaggerUI` but not `Swashbuckle.AspNetCore.SwaggerGen` and `Swashbuckle.AspNetCore.Swagger`.
=> Upgrade swagger from v5.6.3 to v6.4.0

.editorconfig, Directory.Build.props, Directory.Packages.props, W3C.Contracts/W3C.Contracts.csproj, W3C.Domain/W3C.Domain.csproj, W3ChampionsStatisticService.sln, W3ChampionsStatisticService/W3ChampionsStatisticService.csproj, WC3ChampionsStatisticService.UnitTests/WC3ChampionsStatisticService.Tests.csproj
This PR introduces two new configuration files to streamline project management:
Directory.Build.props: Centralized common build settings (such as version numbers and build options) for all projects in the directory and subdirectories, ensuring consistency across the solution.
Directory.Packages.props: Introduced to define consistent NuGet package versions across multiple projects, preventing version mismatches and making dependency management easier.
These changes simplify project maintenance, reduce duplication of settings across individual project files and prevents package version conflicts.
=> use Directory.Build.Props and Directory.Packages.Props

W3ChampionsStatisticService/Cache/ICachedDataProvider.cs, W3ChampionsStatisticService/Cache/InMemoryCacheData.cs, W3ChampionsStatisticService/Matches/MatchesController.cs, W3ChampionsStatisticService/Program.cs, W3ChampionsStatisticService/Services/MatchService.cs
Recently we experienced some website slowness. /api/matches/search is heavily used and does an expensive db query.
My suggestion is to create a MatchService, similar to other services, which leverages our existing in-memory cache. This will cache the results of unique /api/matches/search requests for 15 seconds.
How do I know the caching works? I used the console logs which are removed in the second commit.
=> Cache /api/matches/search

W3ChampionsStatisticService/PlayerProfiles/PlayersController.cs
Apparently this api that was annotated as obsolete was still in use by ChatService. Adding it back.
=> add back api used by chat service

W3C.Domain/MatchmakingService/MatchEventDtos.cs, W3ChampionsStatisticService/Hero/Hero.cs, W3ChampionsStatisticService/Hero/HeroController.cs, W3ChampionsStatisticService/Matches/MatchRepository.cs, W3ChampionsStatisticService/Matches/MatchesController.cs, W3ChampionsStatisticService/Matches/Matchup.cs, W3ChampionsStatisticService/Matches/PlayerOverviewMatches.cs, W3ChampionsStatisticService/Matches/PlayerScore.cs, W3ChampionsStatisticService/Ports/IMatchRepository.cs, W3ChampionsStatisticService/Program.cs, W3ChampionsStatisticService/ReadModelBase/BsonExtensions.cs, W3ChampionsStatisticService/Services/MatchupHeroBackfillService.cs, WC3ChampionsStatisticService.UnitTests/Helpers/TestDtoHelper.cs, WC3ChampionsStatisticService.UnitTests/Heroes/HeroTest.cs, WC3ChampionsStatisticService.UnitTests/Matchups/MatchupDetailTest.cs, WC3ChampionsStatisticService.UnitTests/Matchups/MatchupRepoTests.cs, WC3ChampionsStatisticService.UnitTests/Matchups/MatchupTests.cs
- Add new `Hero` class that specifically for backend to separate from the MM MatchFinishedEvent hero class. This also parses the `icon` path differently. The parsing can be expanded to support custom games later if we want
- Add new `HeroType` enum that's used as an ID for heroes instead of using strings. The enum value is saved in the `Matchup` document and is used for querying and filtering.
- Add hero data for players in `Matchup`. This only adds the enum value as an id, and the level. Strings are handled in the backend/frontend as needed.
- Add backfill service to gradually update historical matchup data to add hero data. This runs as a background task updating in batches of 1000 with a 5 second delay between each batch (set for all `ReadModelHandler` background tasks). Is enabled by …
=> Add Hero data and filtering to Matchup

W3ChampionsStatisticService/Matches/PlayersObfuscator.cs
Currently, you can infer the player via the pings. This PR adds ping anonymization to ongoing matches.
=> Obfuscate ping in ffa

W3ChampionsStatisticService/Filters/SignalRTraceContextFilter.cs, W3ChampionsStatisticService/Hubs/WebsiteBackendHub.cs
The way we pass the tracing context requires that every invoked socket handler has at least one arguments.
SignalR allows to pass an arbitrary number of arguments, even if unmatched, which we're using to transfer the tracing context. Unfortunately, this method does not work for handlers with zero arguments as SignalR has some sort of optimization in place that intercepts the call too early. Hence, I've introduced this placeholder concept.
From the caller side, nothing is going to actually change. I've also added a static check that ensures all handlers have at least one argument so that we don't have the error during invocation but instead during boot.
=> Add tracing placeholder for zero-arg socket methods

W3C.Domain/Repositories/Contracts/IMatchEventRepository.cs, W3C.Domain/Repositories/MatchEventRepository.cs, W3ChampionsStatisticService/Ladder/PlayOverviewHandler.cs, W3ChampionsStatisticService/Ladder/PlayerWinrateHandler.cs, W3ChampionsStatisticService/Matches/MatchReadModelHandler.cs, W3ChampionsStatisticService/PlayerProfiles/GameModeStats/PlayerGameModeStatPerGatewayHandler.cs, W3ChampionsStatisticService/PlayerProfiles/MmrRankingStats/PlayerMmrRpTimelineHandler.cs, W3ChampionsStatisticService/PlayerProfiles/PlayerOverallStatsHandler.cs, W3ChampionsStatisticService/PlayerProfiles/RaceStats/PlayerRaceStatPerGatewayHandler.cs, W3ChampionsStatisticService/PlayerStats/GameLengthForPlayerStatistics/GameLengthForPlayerStatisticsHandler.cs, W3ChampionsStatisticService/PlayerStats/HeroStats/PlayerHeroStatsHandler.cs, W3ChampionsStatisticService/PlayerStats/RaceOnMapVersusRaceStats/PlayerRaceOnMapVersusRaceRatioHandler.cs, W3ChampionsStatisticService/Program.cs, W3ChampionsStatisticService/ReadModelBase/IReadModelHandler.cs, W3ChampionsStatisticService/ReadModelBase/MatchFinishedReadModelHandler.cs, W3ChampionsStatisticService/ReadModelBase/ReadModelExtensions.cs, W3ChampionsStatisticService/W3ChampionsStats/DistinctPlayersPerDays/DistinctPlayersPerDayHandler.cs, W3ChampionsStatisticService/W3ChampionsStats/GameLengths/GameLengthStatHandler.cs, W3ChampionsStatisticService/W3ChampionsStats/GamesPerDays/GamesPerDayHandler.cs, W3ChampionsStatisticService/W3ChampionsStats/HeroPlayedStats/HeroPlayedStatHandler.cs, W3ChampionsStatisticService/W3ChampionsStats/HeroWinrate/HourOfPlayModelHandler.cs, W3ChampionsStatisticService/W3ChampionsStats/MapsPerSeasons/MapsPerSeasonHandler.cs, W3ChampionsStatisticService/W3ChampionsStats/MatchupLengths/MatchupLengthsHandler.cs, W3ChampionsStatisticService/W3ChampionsStats/OverallRaceAndWinStats/OverallRaceAndWinStatHandler.cs, W3ChampionsStatisticService/W3ChampionsStats/PopularHours/PopularHoursStatHandler.cs, WC3ChampionsStatisticService.UnitTests/Matchups/MatchupEventRepoTests.cs, WC3ChampionsStatisticService.UnitTests/ReadModel/MatchFinishedReadModelHandlerTests.cs
In preparation for supporting MatchCanceledEvents, make the different components generic rather than exclusive for MatchFinishedEvent.
=> Make MatchReadModelHandler generic

W3ChampionsStatisticService/Clans/ClanCommandHandler.cs, W3ChampionsStatisticService/PlayerProfiles/GameModeStats/GameModeStatQueryHandler.cs, W3ChampionsStatisticService/Program.cs, W3ChampionsStatisticService/ReadModelBase/AsyncServiceBase.cs, W3ChampionsStatisticService/ReadModelBase/MatchFinishedReadModelHandler.cs, W3ChampionsStatisticService/Services/TrackingService.cs, WC3ChampionsStatisticService.UnitTests/Helpers/TestDtoHelper.cs, WC3ChampionsStatisticService.UnitTests/ReadModel/MatchFinishedReadModelHandlerTests.cs
The tracking service is currently directly injected as an object, which makes it not mockable for tests. This PR refactors this in order to allow mocking it in tests.
=> Make tracking service testable

W3ChampionsStatisticService/Matches/OngoingRemovalMatchCanceledHandler.cs, W3ChampionsStatisticService/Program.cs, W3ChampionsStatisticService/ReadModelBase/IReadModelHandler.cs, W3ChampionsStatisticService/ReadModelBase/MatchCanceledReadModelHandler.cs, W3ChampionsStatisticService/ReadModelBase/MatchEventReadModelHandler.cs, W3ChampionsStatisticService/ReadModelBase/MatchFinishedReadModelHandler.cs, W3ChampionsStatisticService/ReadModelBase/ReadModelExtensions.cs, WC3ChampionsStatisticService.UnitTests/Helpers/TestDtoHelper.cs, WC3ChampionsStatisticService.UnitTests/IntegrationTestBase.cs, WC3ChampionsStatisticService.UnitTests/ReadModel/MatchCanceledReadModelHandlerTests.cs
We are currently not removing ongoing games if they have been canceled; instead, we rely on them being removed when the player starts a new game (and we receive a MatchFinished event for that game).
This can result in an ever-increasing list of ongoing matches; especially when outages cause a significant number of canceled matches.
=> Remove ongoing game if MatchCanceledEvent is received

W3ChampionsStatisticService/Matches/OngoingMatchesCache.cs, WC3ChampionsStatisticService.UnitTests/Helpers/TestDtoHelper.cs, WC3ChampionsStatisticService.UnitTests/Matchups/MatchupDetailTest.cs, WC3ChampionsStatisticService.UnitTests/Matchups/MatchupRepoTests.cs, WC3ChampionsStatisticService.UnitTests/Performance/DBPerformanceTest.cs, WC3ChampionsStatisticService.UnitTests/ReadModel/MatchCanceledReadModelHandlerTests.cs, WC3ChampionsStatisticService.UnitTests/ReadModel/MatchFinishedReadModelHandlerTests.cs
In preparation for the ongoing games cache improvements, make the tracing service testable by introducing a mocking helper.
=> Make tracing service testable

W3ChampionsStatisticService/ReadModelBase/MatchFinishedReadModelHandler.cs, WC3ChampionsStatisticService.UnitTests/ReadModel/MatchFinishedReadModelHandlerTests.cs
Fake events did not always have the state properly set, hence excluding them from the state validation. This is in line with the previous implementation; this strict validation is new.
=> Exclude fake match finished events from match state validation

W3ChampionsStatisticService/Services/PlayerService.cs, WC3ChampionsStatisticService.UnitTests/Player/PlayerTests.cs
For unranked players, we are erroring out on missing data due to the usage of `First` instead of `FirstOrDefault`.
=> Fix null pointer exception for player quantiles when the player is not ranked.

W3C.Domain/Repositories/MongoDbRepositoryBase.cs, W3ChampionsStatisticService/Clans/ClanMembership.cs, W3ChampionsStatisticService/Matches/Matchup.cs, W3ChampionsStatisticService/PersonalSettings/PersonalSetting.cs, W3ChampionsStatisticService/PlayerProfiles/GameModeStats/RankProgression.cs, W3ChampionsStatisticService/PlayerProfiles/MmrRankingStats/PlayerMmrRpTimeline.cs, W3ChampionsStatisticService/PlayerProfiles/PlayersController.cs, W3ChampionsStatisticService/W3ChampionsStats/DistinctPlayersPerDays/DistinctPlayersPerDay.cs, W3ChampionsStatisticService/W3ChampionsStats/GamesPerDays/GamesPerDay.cs
Address this from the migration guide:
> By default, the driver serializes DateTimeOffset values as BSON documents. In previous versions of the driver, the driver serialized these values as BSON arrays by default. To serialize a DateTimeOffset value as an array in v3.0, apply the [BsonRepresentation(BsonType.Array)] attribute to the field.
=> Make DateTimeOffset backwards compatible

W3C.Contracts/Matchmaking/GameMode.cs
This reverts commit 96bedb938c1091c54c71d58132f5e144582c94b6.
With https://github.com/w3champions/website-backend/pull/420 in place, we can now safely add new game modes to the enum without it showing up anywhere unless the mode is active.
=> Reapply "Add risk europe ladder (#416)" (#417)

W3C.Domain/MatchmakingService/MatchEventDtos.cs
This change is entirely backwards compatible and will just address the quirks for JavaScript serialization
=> Add zero to null handling for endTime in Match events

W3ChampionsStatisticService/Program.cs
We currently have a lot of these logs:
> 'Authorization' header found but the scheme is not a 'Basic' scheme."
The root cause is that because I added authentication for BasicAuth and we are running JWT via a custom method rather than a middleware, the basicauth middleware complains because it detects no other handler to handle the authorization header.
We should move JWT into the middleware. For now, we silence the logs though.
=> Supress basic schema log

W3ChampionsStatisticService/Friends/FriendCommandHandler.cs, W3ChampionsStatisticService/Friends/FriendRequestCache.cs, W3ChampionsStatisticService/Hubs/WebsiteBackendHub.cs, WC3ChampionsStatisticService.UnitTests/Hubs/WebsiteBackendHubTests.cs
Implements the ability for users to block other players.
- Adds a `BlockPlayer` method to the `WebsiteBackendHub` to allow users to block other players.
- Implements various tests for the `WebsiteBackendHub` to ensure proper functionality and prevent regressions.
- Introduces interfaces for FriendRequestCache and FriendCommandHandler to make it possible to test.
Used Roo Code to make all these changes. I did run the tests locally, I installed .NET SDK 9.0 (latest) but it didn't work so I had to install 8.0 as well. Should be fine I guess. Very simple addition, just lots of tests to cover all the hub tasks.
=> Adds Block Player Functionality and Tests

W3ChampionsStatisticService/Matches/MatchRepository.cs, W3ChampionsStatisticService/W3ChampionsStats/GameLengths/GameLengthStat.cs, W3ChampionsStatisticService/W3ChampionsStats/GameLengths/GameLengthStatHandler.cs
- Updated Insert method in MatchRepository to handle MongoDB _id modification errors gracefully, ensuring idempotency -> Necessary due to duplicate insertions
- Improved GameLengthStat to skip recording for zero or negative durations -> Necessart due to new cancelled matches having 0 duration
=> Enhance MatchRepository Insert Method and GameLengthStat Handling

W3ChampionsStatisticService/Replays/ReplaysController.cs, W3ChampionsStatisticService/Services/TurnstileService.cs, W3ChampionsStatisticService/WebApi/ActionFilters/TurnstileVerificationAttribute.cs, W3ChampionsStatisticService/WebApi/ActionFilters/TurnstileVerificationFilter.cs, WC3ChampionsStatisticService.UnitTests/Services/TurnstileServiceTests.cs
- Updated TurnstileVerification attribute to include MaxAgeSeconds property for token age validation.
- Modified ReplaysController to enforce a maximum token age of 10 seconds for replay retrieval.
- Enhanced TurnstileService to return detailed verification results, including expiration status.
- Updated TurnstileVerificationFilter to log specific messages for expired tokens.
- Added unit tests for TurnstileService to cover new functionality and edge cases.
=> Enhance Turnstile verification with max age support

W3C.Contracts/Matchmaking/Queue/QueueQuantiles.cs, W3ChampionsStatisticService/Matches/PlayerOverviewMatches.cs, W3ChampionsStatisticService/PlayerProfiles/GameModeStats/PlayerGameModeStatPerGateway.cs
The MMR system uses high precision doubles. Treating them as floats results in dataloss which the DB drives does not like.
=> Replace quantile float with double to match precision
